# Generated by Django 6.1.1 on 2026-09-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APOD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=255)),
                ('media_type', models.CharField(max_length=15)),
                ('media_location', models.CharField(max_length=255)),
                ('explanation', models.CharField(max_length=1024)),
                ('credit', models.CharField(max_length=255)),
                ('copyright', models.CharField(max_length=255)),
                ('alt', models.CharField(max_length=500)),
            ],
        ),
    ]
